"""improved ratings model categories spell

Revision ID: 1b3a02620688
Revises: a1a51a75d376
Create Date: 2026-03-04 11:18:19.194256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3a02620688'
down_revision: Union[str, Sequence[str], None] = 'a1a51a75d376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('lightning', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('facility_quality', sa.Integer(), nullable=False))
    op.drop_column('ratings', 'lighting')
    op.drop_column('ratings', 'facilities_quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('facilities_quality', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ratings', sa.Column('lighting', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ratings', 'facility_quality')
    op.drop_column('ratings', 'lightning')
    # ### end Alembic commands ###
