"""removed cascade delete from place if staff/admin deleted

Revision ID: 4bb95dd7d643
Revises: 4043b0da70c3
Create Date: 2026-03-03 13:40:39.882882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb95dd7d643'
down_revision: Union[str, Sequence[str], None] = '4043b0da70c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('places_user_id_fkey'), 'places', type_='foreignkey')
    op.create_foreign_key(None, 'places', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.create_foreign_key(op.f('places_user_id_fkey'), 'places', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
