"""added the relationship between places and users table and also added foreign key in places table

Revision ID: 58bc092c984e
Revises: 22a2812b8498
Create Date: 2026-01-25 16:24:05.867779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bc092c984e'
down_revision: Union[str, Sequence[str], None] = '22a2812b8498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'places', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'user_id')
    # ### end Alembic commands ###
