"""created ratings table

Revision ID: 6136cdb99e94
Revises: 59f86ac87e10
Create Date: 2026-03-03 22:40:47.710320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6136cdb99e94'
down_revision: Union[str, Sequence[str], None] = '59f86ac87e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('overall', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('cleanliness', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('safety', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('crowd_behavior', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('lighting', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('transport_access', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('facilities_quality', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ratings', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ratings_place_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_place_id_fkey'), 'ratings', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ratings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ratings', 'created_at')
    op.drop_column('ratings', 'facilities_quality')
    op.drop_column('ratings', 'transport_access')
    op.drop_column('ratings', 'lighting')
    op.drop_column('ratings', 'crowd_behavior')
    op.drop_column('ratings', 'safety')
    op.drop_column('ratings', 'cleanliness')
    op.drop_column('ratings', 'overall')
    # ### end Alembic commands ###
