"""changed constraints for the Ratings table from lighting to lightning

Revision ID: 85268927a26f
Revises: d4357669233f
Create Date: 2026-03-07 18:52:16.066416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85268927a26f'
down_revision: Union[str, Sequence[str], None] = 'd4357669233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
