"""added constraints in ratings table

Revision ID: a1a51a75d376
Revises: 6136cdb99e94
Create Date: 2026-03-03 22:44:44.257108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a51a75d376'
down_revision: Union[str, Sequence[str], None] = '6136cdb99e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_place_rating', 'ratings', ['user_id', 'place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_place_rating', 'ratings', type_='unique')
    # ### end Alembic commands ###
