"""added google_sub column in users table for storing the id

Revision ID: b3d3202ce8ae
Revises: 6c1b1108992f
Create Date: 2026-01-25 23:09:04.691976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d3202ce8ae'
down_revision: Union[str, Sequence[str], None] = '6c1b1108992f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
