"""removed pincode from the votes and added nullable=True

Revision ID: c7429fa43e1c
Revises: c97b900f42ee
Create Date: 2026-01-26 14:26:11.310032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7429fa43e1c'
down_revision: Union[str, Sequence[str], None] = 'c97b900f42ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'vote',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('votes', 'pincode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('pincode', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('votes', 'vote',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
