"""changed constraints for the Ratings table in women_safety to safety

Revision ID: d4357669233f
Revises: 1b3a02620688
Create Date: 2026-03-07 18:49:29.412153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4357669233f'
down_revision: Union[str, Sequence[str], None] = '1b3a02620688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
