"""added about_place

Revision ID: f9c2cbd47ab3
Revises: c7429fa43e1c
Create Date: 2026-01-26 20:55:08.948753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c2cbd47ab3'
down_revision: Union[str, Sequence[str], None] = 'c7429fa43e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('about_place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'about_place')
    # ### end Alembic commands ###
