"""added profile column

Revision ID: fe15ac9bd09a
Revises: b3d3202ce8ae
Create Date: 2026-01-25 23:32:40.521809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe15ac9bd09a'
down_revision: Union[str, Sequence[str], None] = 'b3d3202ce8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_url')
    # ### end Alembic commands ###
